add team check to release workflow

diff --git a/.github/workflows/run-release.yaml b/.github/workflows/run-release.yaml
--- a/.github/workflows/run-release.yaml
+++ b/.github/workflows/run-release.yaml
@@ -8,6 +8,17 @@ on:
         required: false
 
 jobs:
+  check-team:
+    runs-on: ubuntu-latest
+    steps:
+    - env:
+        GITHUB_TOKEN: ${{ secrets.ADH_BOT_ORG_TOKEN }}
+      run: |
+        access=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/adh-partnership/teams/maintainers-frontend/memberships/${{ github.actor }})
+        if [ "$(echo $access | jq -r .state)" != "active" ]; then
+          echo "${{ github.actor }} is not a member of the maintainers-frontend team and cannot run this workflow"
+          exit 1
+        fi
   release:
     runs-on: ubuntu-latest
     steps:
